=== Srujithchaithanya1/Lab/Lab/5/exp6.dtd
<!ELEMENT bookDet (Book+)>
<!ELEMENT Book (Bookname,Author,Publisher,Price)>
<!ELEMENT Bookname (#PCDATA)>
<!ELEMENT Author (#PCDATA)>
<!ELEMENT Publisher (#PCDATA)>
<!ELEMENT Price (#PCDATA)>

=== Srujithchaithanya1/Lab/Lab/5/exp6.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="exp6.xsl"?>
<!DOCTYPE bookDet SYSTEM "exp6.dtd">
<?xml-model href="exp6.xsd"?>
<bookDet>
    <Book>
        <Bookname>WP</Bookname>
        <Author>Giri Babu</Author>
        <Publisher>CVR</Publisher>
        <Price>650</Price>
    </Book>
    <Book>
        <Bookname>CPG</Bookname>
        <Author>Sravan</Author>
        <Publisher>NIST</Publisher>
        <Price>399</Price>
    </Book>
    <Book>
        <Bookname>CN</Bookname>
        <Author>Forouzan</Author>
        <Publisher>Technical</Publisher>
        <Price>500</Price>
    </Book>
</bookDet>
